baseURL = "//xyzroe.cc/"

relativeURLs = true
canonifyURLs = true
languageCode = "en-us"
theme = "m10c"
paginate = 10
title = "xyzroe's blog"
googleAnalytics = "UA-203059197-1"
enableRobotsTXT = true

staticDir = ["static", "projects"]


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "xyzroe"
  description = "Technical automation, some DIY stuff, little useful scripts, electronic devices development"

  avatar = "img/avatar.png"
  menu_item_separator = " - "
  [[params.social]]
    icon = "send"
    name = "Telergam"
    url = "https://t.me/xyzroe"
  [[params.social]]
    icon = "at-sign"
    name = "Email"
    url = "mailto:i@xyzroe.cc"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/xyzroe"

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#bdbdbd"
  lightestColor = "#fcba47"
  primaryColor = "#ffa200"

[markup.goldmark.renderer]
  unsafe = true
